const images = {
	logo_w: '/assets/images/logo-w.png',
	logo_b: '/assets/images/logo-b.svg',
	logo_orca: '/assets/images/logo-orca.png',
	profile: '/assets/images/profile.png',
	back_b: '/assets/images/back-b.png',
	back_w: '/assets/images/back-w.png',
	go_b: '/assets/images/go-b.png',
	go_w: '/assets/images/go-w.png',
	view: '/assets/images/view.svg',
	search: '/assets/images/search.svg',
	backwithletter: '/assets/images/backwithletter.svg',
	baropen: '/assets/images/baropen.svg',
	barclose: '/assets/images/barclose.svg',
	vector36: '/assets/images/vector36.svg',
	beamworks: '/assets/images/beamworks.png',
	logo_s: '/assets/images/logo-s.png',
	back_arrow: '/assets/images/back-arrow.svg',
	paging_bar: '/assets/images/paging_bar.svg',
	dot_w: '/assets/images/dot-w.svg',
	dot_g: '/assets/images/dot-g.svg',
	menu: '/assets/images/menu.svg',
	language: '/assets/images/language.svg',
	gnb_back: '/assets/images/gnb-back.svg',
};

export default images;
